#!/bin/sh

export FILEBOT_NODE_HOST="0.0.0.0" # bind to all interfaces

export FILEBOT_CMD="filebot"
export FILEBOT_CMD_CWD="/volume1"
export FILEBOT_CMD_UID=`id -u`
export FILEBOT_CMD_GID=`id -g`

export FILEBOT_NODE_CLIENT="/usr/local/filebot-node/client"

# --optimize_for_size (Enables optimizations which favor memory size over execution speed.)
# --use_idle_notification (Use idle notification to reduce memory footprint.)
node --optimize_for_size --use_idle_notification "/usr/local/filebot-node/server/app.js"
