#!/bin/sh -xu

inotifywait -m "$1" -e create -e moved_to --exclude '/[.@]' --format '%w%f' | stdbuf -oL uniq | while read -r FILE; do
	if file --mime-type "$FILE" | egrep "directory|video|audio"; then
		filebot -script fn:amc --action duplicate --conflict auto -non-strict --log-file amc.log --def excludeList=".excludes" unsorted=y music=y artwork=y "$@"
	fi
done
